### ISSUE TITLE
Allow user to enter buffer radius

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#10]
Enhancement suggestion: allow users to enter a radius as well as or instead of the slider. The slider seems to skip numbers, e.g. it goes from 483 to 501 and I cannot get it to have a 500 foot buffer.

Should there be an upper limit to the buffer distance?

**Comment by marikavertzonis** [comment]
tested build 1.0.97 on windows 10 and mac 10.9.5.
The entering of both the buffer and units worked well for different scales. Successfully created TPK for route from Melbourne to Sydney with buffer in km's, and also routes around Melbourne with buffers of m's.
