### ISSUE TITLE
Manually input a tiled service URL to generate a TPK

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#2]
Ability to manually point to a service URL of a tiled service.
This might be because I have not registered the basemap as a layer in my AGO account or for whatever reason the crawling through my AGO Account did not pick up on the service.
Could also have better error reporting to user if this fails.
E.g. Could not add service as Export Tiles is not enabled, please refer to the help and contact the data owner to enable this
![d4d39706-bd55-11e6-96d8-cf13094fcf87](https://cloud.githubusercontent.com/assets/3229911/21205555/e824ab96-c2b0-11e6-83f1-7543907de744.png)

**Comment by defiantgoat** [comment]
Added with version 1.0.89

**Comment by marikavertzonis** [comment]
tested build 1.0.97 and 1.1.2 on windows 10, mac 10.9.5 and ubuntu 14 by adding
http://featureservices.thelist.tas.gov.au/arcgis/rest/services/Basemaps/Topographic/MapServer.
