### ISSUE TITLE
Remember Manually Entered Tile Services

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#27]
Provide the ability to remember manually entered tile services so that they appear everytime the user uses the application. Also provide a method for deleting it via the tile service context menu.

Related to #2

**Comment by JohnHasthorpe** [comment]
Added service and then closed and reopened the app.
Verified as working on:

* Ubuntu Linux 16.04
* Macbook Pro Mac OS 10.11.6
* Surface Book Pro - Windows 10
