### ISSUE TITLE
Download Software Update always redirecting to old version

### ISSUE THREAD

**Issue by IsmaelInRedlands** [Esri/TilePackageKreator#34]
See video: https://youtu.be/U5ariaKUiAs

**Comment by marikavertzonis** [comment]
This behavior is expected. In your video when you go to the hockeyapp page see in the top right hand corner that you are not signed in. Only build 1.0.87 is currently publicly available. If you sign into hockeyapp on that page, and then go back to Tile Package Kreator and click the newer version, you will see it in hockeyapp.

Only members of the Esri Labs Preview team in hockeyapp should be able to download the non public versions.

**Comment by marikavertzonis** [comment]
@defiantgoat - is there a way to distinguish between public and private build? If so, can we stylize the list to differentiate between the two?

**Comment by defiantgoat** [comment]
Code has been amended to only show public (unrestricted) versions in the updates dialog.

**Comment by marikavertzonis** [comment]
installed 1.1.2 on windows 10, mac 10.9.5 and ubuntu 14. as the current version is later than the last public version, nothing is shown. need to wait till next release to verify.

**Comment by JohnHasthorpe** [comment]
Verified that this is now all working
