### ISSUE TITLE
Basic geosearch

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#35]
Basic address / location geosearch.

**Comment by survey123** [comment]
+1

**Comment by slibby** [comment]
👍 on this, especially when exporting imagery, you have no way to find the place you're looking for without memorizing how it looks from above and zooming to it from the global view.

**Comment by defiantgoat** [comment]
This is available in v 1.2.6 and greater.

**Comment by defiantgoat** [comment]
Available with version 1.2.19 and greater.

**Comment by JohnHasthorpe** [comment]
Verified working on:

* Ubuntu Linux 16.04
* Macbook Pro Mac OS 10.11.6
* Surface Book Pro - Windows 10
