### ISSUE TITLE
Switch tile service while inside the map view rather than going back to gallery.

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#38]
Ability to switch the tile services once inside the map view rather than having to go back to the gallery and come back.

**Comment by defiantgoat** [comment]
This is available in version 1.2.6 and greater.

**Comment by defiantgoat** [comment]
Available with version 1.2.19 and greater.

**Comment by JohnHasthorpe** [comment]
Verified working on: 

* Ubuntu Linux 16.04
* Macbook Pro Mac OS 10.11.6
* Surface Book Pro - Windows 10
