### ISSUE TITLE
Handle long running requests in AvailableServicesInfoRequest better

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#4]
UI stalls when one of these elements takes along time to respond, so need to add a quicker timeout to the Network Request.

Issue added to appstudio-framework repo > # 119

**Comment by defiantgoat** [comment]
@marikavertzonis This is a new setting in the Settings page. You can set the timeout length. This basically will set a time in which to kill unresponsive network requests (which can sometimes take up to 1 minute or greater to return back a failure). This helps the UI not get blocked for a long period due to one failed request regarding a tile service in the Create tile package gallery.

**Comment by marikavertzonis** [comment]
using our dev org that is known to have some unresponsive services, testing with 3.1.14 on windows desktop 10 and linux 16 i see with the new check box **unchecked**  it takes 3min14sec to return 17 out of the 27 available tile services. (same time on both machines)
when i went back and checked the new box - keeping the default timeout of 7 seconds - i then see the same 17 out 27 services returned after only 10seconds on both machines.
