### ISSUE TITLE
Can't install 'TilePackageKreator_1_1_2.dmg'

### ISSUE THREAD

**Issue by RoelOortgiesen** [Esri/TilePackageKreator#43]
Hi Guys,

I really would like to experiment with the Tile Package Kreator but it doesn't want to install on my Macbook Pro (10.12.3). 

It says: 
“Install TilePackageKreator” is damaged and can’t be opened. You should eject the disk image."

Anyone got a solution for this?

Cheers!

**Comment by marikavertzonis** [comment]
@RoelOortgiesen - please try downloading the Mac installation file for Tile Package Kreator again. We made a fix that should result in you no longer getting this message.
