### ISSUE TITLE
Download links don't work ... no version available?

### ISSUE THREAD

**Issue by timhaverland-noaa** [Esri/TilePackageKreator#44]
http://links.esri.com/esrilabs/tile-package-kreator-windows

Leads to:

https://rink.hockeyapp.net/apps/0434b867939a4208a513fabffa3fb4ad

And that page says:

No version available

**Comment by marikavertzonis** [comment]
@timhaverland-noaa - please try again - they have been reactivated.

these seem to periodically become unshared. i'm leaving this issue open while i investigated why they keep getting unshared.

**Comment by marikavertzonis** [comment]
issue resolved. builds were being automatically update when build system was update. automatic updates have been disabled.
