### ISSUE TITLE
Ability to draw polygon on map

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#47]
Add ability to draw a polygon on the map in addition to envelope and line features.

**Comment by defiantgoat** [comment]
Available with version 1.2.19 and greater.

**Comment by JohnHasthorpe** [comment]
Verified working on 
* Ubuntu Linux 16.04
* Macbook Pro Mac OS 10.11.6
* Surface Book Pro - Windows 10
