### ISSUE TITLE
Missing fonts in Windows 10

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#51]
NotoSans and custom icon font true type families are not rendering in Tile Package Kreator in Windows 10. Reboot of machine didn't fix the issue.

Specifications for reporting computer:
OS Name          Microsoft Windows 10 Enterprise
Version 10.0.14393 Build 14393
Other OS Description    Not Available
OS Manufacturer           Microsoft Corporation
System Manufacturer     Dell Inc.
System Model   Precision 5510
System Type      x64-based PC
BIOS Version/Date         Dell Inc. 1.2.21, 2/17/2017
SMBIOS Version 2.8
Device Guard Virtualization based security           Not enabled
Hyper-V - VM Monitor Mode Extensions Yes
Hyper-V - Second Level Address Translation Extensions   Yes
Hyper-V - Virtualization Enabled in Firmware       Yes
Hyper-V - Data Execution Protection       Yes

![unnamed-1](https://user-images.githubusercontent.com/3229911/27066467-c9bc47fc-5047-11e7-866b-de3284732e59.png)
![unnamed](https://user-images.githubusercontent.com/3229911/27066468-c9d3826e-5047-11e7-8a4d-5a5d00b93df5.png)

**Comment by defiantgoat** [comment]
@IsmaelInRedlands This should be fixed in version 1.2.6 and greater.

**Comment by IsmaelInRedlands** [comment]
Some improvement. Highlighting with green arrows the areas where I still find issues

![tpk](https://user-images.githubusercontent.com/5918689/27882279-e6dc1c82-6180-11e7-8aa2-0f4e750d1c23.png)

![tpk2](https://user-images.githubusercontent.com/5918689/27882347-2b958af2-6181-11e7-86f8-abb78061002a.png)

![tpk3](https://user-images.githubusercontent.com/5918689/27882410-6741fe50-6181-11e7-819c-a426891ea953.png)

**Comment by defiantgoat** [comment]
@IsmaelInRedlands Thanks for testing. I will work on the custom icon font now.

**Comment by defiantgoat** [comment]
This issue has been resolved as of build 1.2.22 and will be part of the 1.3 release.
