### ISSUE TITLE
Support Zoom levels below z19

### ISSUE THREAD

**Issue by slibby** [Esri/TilePackageKreator#56]
Several services, like the World Imagery for Export service, support additional zoom levels for export down to 1:70 scale, as seen here: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Imagery/MapServer (requires token)

Currently, TPK seems to have an arbitrary Level 19 limit, this should be based on the maximum tile scale reported by the service, as it is when there is a scale below z15.

**Comment by slibby** [comment]
@defiantgoat I believe removing this ternary would accomplish this: https://github.com/Esri/TilePackageKreator/blob/master/ExportView.qml#L63

In this case I don't see an issue with removing it - interesting in your feedback when you have a chance.

**Comment by defiantgoat** [comment]
@slibby I've updated the app so that 21 is the default max level. I've also added a settings page that will allow the user to expose all levels if they want. It is my experience, however, that the export services tend to fail always when requesting above 21, no matter how small the area of interest.

Still working on v 1.3. Hope to have the version ready to go very soon.

**Comment by defiantgoat** [comment]
@marikavertzonis  The map now allows up to level 21. You can also allow all levels (typically up to 23) by using the Settings page which is new with v 1.3

**Comment by marikavertzonis** [comment]
testing with 1.3.14 on windows and mac in the area of New York where greatest level of tiles is expected. successfully exported streetmap layer, area of Manhattan with levels of 
 - 18-20 (size 105MB) 
 - 18-21 (reported by the app, est. size 683MB and number of tiles 57913) 
 - 15-19 (size 125MB)

when I went for a smaller area and levels 20-22 and the streetmap layer, it didn’t fail, but the tpk had no visible tiles in it. with the world imagery layer, it didn’t fail, but this time it did include tiles.

i observed all the resultant tpk's in an appstudio app that displays tpks:
![image](https://user-images.githubusercontent.com/5713624/39170203-08df9892-47de-11e8-9478-f9e1d09b8b6d.png)

specific issue regarding failed exports, separated out to https://github.com/Esri/TilePackageKreator/issues/72
