### ISSUE TITLE
Support .shp files with geometry

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#60]
Similar to geojson, support for .shp or .xml files with geometry.

**Comment by defiantgoat** [comment]
@marikavertzonis To test you drag and drop the .prj and .shp files onto the map. Currently only supports shapefiles that include line or polygon features. Other features will be parsed by the application, but an error message will show letting the user know that the feature type isn't supported and won't render on the map.

Good sources for shapefiles and/or geojson I have found:

https://gis-pdx.opendata.arcgis.com/
https://catalog.data.gov/dataset

**Comment by marikavertzonis** [comment]
testing with 1.3.11 on windows 10, many shapefiles work as expected. i've copied some exceptions to  `\\melstorage1\data\Marika\shapefiles not working in TPK` for investigation. these either do nothing or crash the app.

**Comment by defiantgoat** [comment]
@marikavertzonis The issues with loading these shapefiles have been addressed in v 1.3.13.

**Comment by marikavertzonis** [comment]
tested with 1.3.14 on
 - windows classic and mac - drag and drop works as expected on the shapefiles described above and others
 - windows uwp - nothing happens - there are other symptoms that make this look like its to do with file system definitions on uwp - this is split off to #71 
 - ubuntu 16 and 17 - drag and drop of these shapefiles results in the error message 'this shapefile contains no geometry'. @defiantgoat have you seen this on ubuntu?

**Comment by marikavertzonis** [comment]
more testing on ubuntu and when i copy the shapefiles locally i can drag and drop them successfully onto the TPK map and see the expected polygons and lines. dragging from the network location on my machine didn work - but it did on @defiantgoat 's machine.
