### ISSUE TITLE
Renamed .tpk disappeared in Survey123

### ISSUE THREAD

**Issue by yingwoei** [Esri/TilePackageKreator#64]
By default, the Survey123 field app will label any offline map loaded as "Layers". I followed the steps in the link below to rename the "Layers" so that I can differentiate them when I have multiple offline maps loaded. However, the renamed map disappeared when I republished my survey. 

Below is my detailed workflow:
1. change the extension from .tpk to .zip
2. extract the files
3. open iteminfo.xml in Notepad
4. rename the title at <title>Layers</title>
5. zip the file and change the extension from .zip to .tpk

Below is the link:
https://community.esri.com/groups/survey123/blog/2017/01/31/taking-your-maps-offline-with-tile-package-creator

I would appreciate if anyone know how to resolve this issue. Thank you very much!

**Comment by defiantgoat** [comment]
@yingwoei 

TPKs aren't zip files, they are 7-zip (http://7-zip.org ) files.  You will need to use 7-zip tools to manipulate them.

See this related article about unzipping and rezipping other types of 7zip archives: https://gis.stackexchange.com/questions/122673/how-to-correctly-uncompress-and-re-compress-an-msd-file-using-7zip-from-command

**Comment by yingwoei** [comment]
@defiantgoat 
This is long overdue, but thank you very much for pointing this out! It is really tricky in renaming the tile packages. I find 7-zip a very good tool to make edits within the zipped file.
