### ISSUE TITLE
Allow users to change the search query used to find tile services.

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#67]
The user should be allowed to change the query used to search for services that allow for exporting tiles. Currently on Map Services are included in the default search, but Image Services also allow exporting of tiles.

**Comment by defiantgoat** [comment]
In Settings, user can now change the search query, as well as always return to the default if the search query becomes corrupted.

![screen shot 2018-04-04 at 12 43 42 pm](https://user-images.githubusercontent.com/3229911/38285917-ec6163ae-3805-11e8-8f84-b01e5fca28d7.png)

**Comment by marikavertzonis** [comment]
tested with 3.1.14 in a few ways and it mostly appears to be behaving as expected with no crashing or failures. hard to be sure without many different services available.
 - changed the query to type:"Image Service" AND owner:esri AND title:(for Export) and it identified 318 services of which it reported that none had tiles for export. exited gracefully.
 - was able to return to the default query after i changed it
 - i published my own image service, and it does appear in the gallery of services to choose from, but when i attempt to export i get a message 'export failed. operation not supported'. @defiantgoat the service is in our org and called RiversideImageService. use the search of 'Riverside' to find the tiles before drawing an extent for export.

**Comment by defiantgoat** [comment]
@marikavertzonis An external user has been provided with a stable version of 1.3 to test against Image Services.

**Comment by defiantgoat** [comment]
@marikavertzonis If a user goes to settings from the gallery and updates the search query, when they return to the gallery it will refresh based on the new query as of v1.3.29

**Comment by marikavertzonis** [comment]
tested 1.3.29 on windows desktop 10, ubuntu 16 and macos 10.13 and i see that when i change the query and return to the gallery, it automatically refreshes.
