### ISSUE TITLE
Unexpected file path used on UWP

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/TilePackageKreator#71]
Two places where this has been evident are:
1. Unexpected local file destination when creating a TPK
    - on windows classic i see the expected ~users/username/ArcGIS/My Tile Packages/ destination for my created tile package
    - with UWP installed on same machine a created TPK is instead created at ~users/username/AppData/Local/Packages/somelongguid/LocalState/ArcGIS/My Tile Packages/
2. Drag and drop files for extent doesn't work
    - attempting to verify #60 in build 1.3.14 - and no shp's files can be drag / dropped (they can on the equivalent windows classic build)

**Comment by defiantgoat** [comment]
@marikavertzonis Drag and Drop and selecting a specific location to save a tile package to locally will not be possible in UWP builds until further investigation is completed. It seems that UWP apps currently don't have the ability to write to non-sandboxed locations or read from file paths in certain scnearios (specifically via file urls collected via Drag and Drop operations).

**Comment by marikavertzonis** [comment]
More research:
The output in the file path described above (ie: 
~users/username/AppData/Local/Packages/somelongguid/LocalState/ArcGIS/My Tile Packages/ )
is only kept there short term. The tpk that i created when i last tested was no longer there, but the new one i created today was.
Have created issue in the framework to improve this location here https://devtopia.esri.com/Melbourne/appstudio-framework/issues/559

**Comment by marikavertzonis** [comment]
Windows Universal will not be supported. Instead, MSIX files will be created from the Windows build, and made available in the Microsoft Store.
