### ISSUE TITLE
After a failed export, can not change settings and attempt another export until change service

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/TilePackageKreator#72]
whilst trying to test #56, i repeatedly got caught by not being able to export (to large an area or levels not available), and then could not readjust my settings (levels, title, save to) and just click export again, without selecting another service and then reselecting my service. the other problem with the service reselection is that, I loose my area of interest and have to define that again.

**Comment by defiantgoat** [comment]
@marikavertzonis The settings button is now disabled on Export View. On the Gallery of available services, if the settings are changed and the user goes back to the gallery, the gallery will now be updated with the changes in the search query.

**Comment by marikavertzonis** [comment]
tested with 1.3.28 on windows desktop 10, ubuntu 16 and macos 10.13 and now after unsuccessfully exporting, i see the export button is greyed out and not until i change the basemap / extent / file name is it re-enabled.
