### ISSUE TITLE
Allow for zoom level range when exporting

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#8]
Allow for dynamic options when selecting zoom levels of created tile package. If I am only wanting a tile package at the extent of zoom levels 13-15, I also have to create zoom levels 1-12 along with it. All scales (zoom levels) may not be desired by end user. Here is an example of viewing the published package at scale 2.

Note: This will be much easier to implement when RangeSlider is available with Qt 5.7 and QuickControls 2.0. At this point, to implement will require a custom range slider to be built, or remove the slider all together and just have a text field(s) for entry.

**Comment by defiantgoat** [comment]
This UI enhancement might also include a visible indicator of the level: 
![c71257f2-5580-11e6-99b4-6d89ade236fd](https://cloud.githubusercontent.com/assets/3229911/21207142/7f07532a-c2ba-11e6-847f-75275f31d9ae.png)

**Comment by defiantgoat** [comment]
This is available in version 1.2.6 and greater.

**Comment by defiantgoat** [comment]
Available with version 1.2.19 and greater.

**Comment by JohnHasthorpe** [comment]
Created a tile package for select scale ranges online and locally. Verified that the tile package contained the appropriate layers and viewed in web map and the field device.

Verified on

* Ubuntu Linux 16.04
* Macbook Pro Mac OS 10.11.6
* Surface Book Pro - Windows 10
