### ISSUE TITLE
Recreate product icon in vector format

### ISSUE THREAD

**Issue by davismmarques** [Esri/TilePackageKreator#83]
Recreate product icon in an appropriate vector format (ex. Illustrator). Add design file into the repo.

**Comment by davismmarques** [comment]
Original TPK logo: https://github.com/Esri/TilePackageKreator/blob/master/appicon.png
Background sources for icons: https://github.com/ArcGIS/esri-product-logos

**Comment by davismmarques** [comment]
@spatialdude @marikavertzonis @phil-wilson Do you want to update the product icon to match the [current ESRI icon scheme](https://user-images.githubusercontent.com/29716057/97457884-66771100-18f7-11eb-910c-6ad0fa601e44.png) or do you prefer we try and recreate the old one exactly?

Katelyn Seitz gave me a vector implementation of the current icon background. I then recreated the word mark and badge  manually and added that on top.  Here's a mockup of the new (left) and old (right) for comparison:

![Screen Shot 2021-02-26 at 2 08 20 pm](https://user-images.githubusercontent.com/66241247/109249588-19bb2c80-783c-11eb-90d5-f5cca1bec2f7.png)

**Comment by phil-wilson** [comment]
@davismmarques My thoughts would be new design, the one on the left looks better and more consistent with the other icons we now have for other apps.

**Comment by davismmarques** [comment]
Updated TPK logo attached below. Should we have this reviewed by the Creative Labs folks?

[tpk-logo.zip](https://github.com/Esri/TilePackageKreator/files/6058253/tpk-logo.zip)

**Comment by marikavertzonis** [comment]
@uabeysinghe - this icon is good for using in 1.4.1 - please incorporate this into the app.
