### ISSUE TITLE
Migrate to AppStudio 5.0

### ISSUE THREAD

**Issue by uabeysinghe** [Esri/TilePackageKreator#84]
Migrate Tile Package Kreator to AppStudio 5.0

**Comment by uabeysinghe** [comment]
Hi @marikavertzonis, this issue along with https://github.com/Esri/TilePackageKreator/issues/50 is now ready for verification. Thanks!

**Comment by marikavertzonis** [comment]
tested 1.4.1 on windows 10, and ubuntu 20
i see buttons appear and operate, and text alignment on screen is as expected.
