### ISSUE TITLE
Add ArcGIS Enterprise connection

### ISSUE THREAD

**Issue by azinsharaf** [Esri/TilePackageKreator#89]
Hi, How can I add ArcGIS Enterprise connection as a new Portal? There is no "add portal" button.

![Tile_Package_Kreator](https://user-images.githubusercontent.com/10101468/127711091-4697f49d-d31f-4a28-9855-64ca647fd771.png)

**Comment by justinljw** [comment]
The "Add Portal" was working in the previous version [#1](https://github.com/Esri/TilePackageKreator/issues/1). 
Investigated the app and found the issue was caused by previous qt imports upgrade. 
Assigned @uabeysinghe to resolve this issue.

**Comment by uabeysinghe** [comment]
@justinljw, I've made the necessary changes, could you please verify this branch [uvi10859-addPortalButton#89](https://github.com/Esri/TilePackageKreator/tree/uvi10859-addPortalButton%2389). Thanks for the help with debugging!

**Comment by marikavertzonis** [comment]
Testing only successfully completed on Windows on Mac. 

On Ubuntu additional certificate installation issues incurred, which prevented testing completion. Not considering this as a showstopper - the 1.5 Ubuntu version will be made available, but no guarantee on its ability to connect to Enterprise can be given. If required, create new issue specifically for Enterprise connectivity on Ubuntu.
