### ISSUE TITLE
No way to progress after Portal login

### ISSUE THREAD

**Issue by maphew** [Esri/TilePackageKreator#94]
I've installed TPK from Microsoft Store. When run it says v1.5.1. I was successful in adding an ArcGIS Enterprise portal and exited the app. 

On restart (and every time since) it shows a "Sign in" page with message "Invalid client_id". 
Using the 'login' link seemlessly uses our active directory / office 365 sign in the same way all our other Windows web apps do. After login I see the rest api page, confirming login succeeded. 

There's no apparent way to progress to anything else. The row of black and grey icons across the top can't be clicked on.

![image](https://github.com/Esri/TilePackageKreator/assets/486200/20df2714-b1a6-41c6-bc66-6ea7ebfa6075)

**Comment by maphew** [comment]
Still that same problem and no new comments or source activity from the authors. I guess this is abandonware.

**Comment by tedrick** [comment]
Hi Matt,

To my knowledge, TPK was never added to the default apps pre-registered in an ArcGIS Enterprise's item store.  This results in the `invalid client_id` message as you would need to create an application entry to register the app. Additionally, if using the pre-built version, you would need to then update the client_id of the item to match the client_id of the pre-built app.

**Comment by maphew** [comment]
hrrm, if I'm understanding the gist of this, creating an application entry is something that the Enterprise server admins need to do? If I point them to this issue will it automatically make sense to them, or do I need to supplement with some other info also?

**Comment by marikavertzonis** [comment]
ah thanks for the reminder @tedrick! and of course now, I realize I've somewhat answered this question before here https://github.com/Esri/TilePackageKreator/issues/89#issuecomment-940512745 🤦‍♀️

See this [wiki ](https://github.com/Esri/TilePackageKreator/wiki/Add-Tile-Package-Kreator-as-a-registered-application-to-ArcGIS-Enterprise) for the steps needed @maphew
